/* ══════════════════════════════════════════
   Good Days 갤러리 LQIP blurDataURL 사전 생성 (S121)

   plaiceholder 로 42장 webp 의 base64 blurDataURL 을 생성하고
   `src/lib/gooddaysBlur.ts` 로 export. 빌드 타임 1회 실행.

   실행: npx tsx scripts/generate-gallery-blur.ts
   ══════════════════════════════════════════ */

import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { getPlaiceholder } from 'plaiceholder';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const NEXT_ROOT = path.join(__dirname, '..');
const PUBLIC_DIR = path.join(NEXT_ROOT, 'public');
const GALLERY_DIR = path.join(PUBLIC_DIR, 'images', 'gallery');
const OUTPUT_FILE = path.join(NEXT_ROOT, 'src', 'lib', 'gooddaysBlur.ts');

type Entry = {
  src: string;
  blurDataURL: string;
  width: number;
  height: number;
};

async function main(): Promise<void> {
  const files = (await fs.readdir(GALLERY_DIR))
    .filter((f) => f.endsWith('.webp'))
    .sort();

  if (files.length === 0) {
    throw new Error(`No webp files in ${GALLERY_DIR}`);
  }

  console.log(`[blur] generating LQIP + dimensions for ${files.length} images...`);

  const entries: Entry[] = [];
  for (const file of files) {
    const filePath = path.join(GALLERY_DIR, file);
    const buffer = await fs.readFile(filePath);
    /* getPlaiceholder 가 sharp 기반 — base64 LQIP + metadata.{width,height} 동시 반환.
       width/height 는 yet-another-react-lightbox Zoom plugin 활성화 조건 (S121). */
    const { base64, metadata } = await getPlaiceholder(buffer, { size: 10 });
    entries.push({
      src: `/images/gallery/${file}`,
      blurDataURL: base64,
      width: metadata.width,
      height: metadata.height,
    });
    process.stdout.write('.');
  }
  process.stdout.write('\n');

  const header = `/* AUTO-GENERATED by scripts/generate-gallery-blur.ts — DO NOT EDIT MANUALLY.
   Re-generate via: npx tsx scripts/generate-gallery-blur.ts
   Source: public/images/gallery/*.webp (${files.length} files) */
`;

  const body = `export type GdBlurEntry = {
  blurDataURL: string;
  width: number;
  height: number;
};

export const GD_BLUR_MAP: Record<string, GdBlurEntry> = ${JSON.stringify(
    Object.fromEntries(
      entries.map((e) => [
        e.src,
        { blurDataURL: e.blurDataURL, width: e.width, height: e.height },
      ]),
    ),
    null,
    2,
  )};
`;

  await fs.writeFile(OUTPUT_FILE, header + '\n' + body, 'utf8');
  console.log(`[blur] wrote ${OUTPUT_FILE}`);
  const totalBytes = entries.reduce((sum, e) => sum + e.blurDataURL.length, 0);
  console.log(`[blur] payload total ≈ ${(totalBytes / 1024).toFixed(1)} KB`);
}

main().catch((err) => {
  console.error('[blur] FAILED:', err);
  process.exit(1);
});
